# Generated by Django 5.1.5 on 2025-01-26 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('min_salary', models.IntegerField()),
                ('max_salary', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='settings.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='settings.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='settings.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fullname', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('extra_description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='settings.country')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vacancy.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacancyLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=512, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('job_schedule', models.CharField(blank=True, max_length=512, null=True)),
                ('work_type', models.CharField(blank=True, max_length=512, null=True)),
                ('city', models.CharField(blank=True, max_length=256, null=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies_languages', to='settings.language')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies_languages', to='vacancy.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
