# Generated by Django 5.1.5 on 2025-02-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_vacancy_max_salary_alter_vacancy_min_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='currency',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
