# Generated by Django 5.1.5 on 2025-01-29 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_alter_categorylanguage_category_and_more'),
        ('vacancy', '0002_delete_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies_languages', to='settings.language'),
        ),
    ]
