# Generated by Django 5.1.5 on 2025-01-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylanguage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_languages', to='settings.category'),
        ),
        migrations.AlterField(
            model_name='categorylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories_languages', to='settings.language'),
        ),
        migrations.AlterField(
            model_name='companylanguage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_languages', to='settings.company'),
        ),
        migrations.AlterField(
            model_name='companylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies_languages', to='settings.language'),
        ),
        migrations.AlterField(
            model_name='countrylanguage',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_languages', to='settings.country'),
        ),
        migrations.AlterField(
            model_name='countrylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries_languages', to='settings.language'),
        ),
    ]
