# Generated by Django 5.1.5 on 2025-02-11 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_faq_faqlanguage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='key',
            field=models.CharField(max_length=2048),
        ),
    ]
