# Generated by Django 5.1.5 on 2025-02-11 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0003_alter_faq_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqlanguage',
            name='value',
            field=models.TextField(blank=True, null=True),
        ),
    ]
