# Generated by Django 5.1.5 on 2025-02-11 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_alter_faqlanguage_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='faqlanguage',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
