# Generated by Django 5.1.5 on 2025-02-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0005_faqlanguage_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='banners/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
