# Generated by Django 5.1.5 on 2025-02-02 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('fullname', models.CharField(max_length=512)),
                ('phone_number', models.CharField(max_length=512)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('fullname', models.CharField(max_length=256)),
                ('gender', models.CharField(blank=True, max_length=256, null=True)),
                ('marital_status', models.CharField(blank=True, max_length=123, null=True)),
                ('birthday_data', models.DateTimeField(blank=True, null=True)),
                ('region', models.CharField(blank=True, max_length=123, null=True)),
                ('phone_number', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('languages', models.CharField(blank=True, max_length=1024, null=True)),
                ('country', models.CharField(blank=True, max_length=256, null=True)),
                ('job_type', models.CharField(blank=True, max_length=512, null=True)),
                ('experience', models.CharField(blank=True, max_length=256, null=True)),
                ('level_of_education', models.CharField(blank=True, max_length=1024, null=True)),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vacancy.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
