# Generated by Django 5.1.5 on 2025-01-25 11:42

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name_uz', models.CharField(max_length=512, verbose_name='Name_uz')),
                ('name_eng', models.CharField(max_length=512, verbose_name='Name_eng')),
                ('name_ru', models.CharField(max_length=512, verbose_name='Name_ru')),
                ('order', models.PositiveIntegerField(default=1, verbose_name='Order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name_uz', models.CharField(max_length=512, verbose_name='Name_uz')),
                ('name_eng', models.CharField(max_length=512, verbose_name='Name_eng')),
                ('name_ru', models.CharField(max_length=512, verbose_name='Name_ru')),
                ('image', models.ImageField(upload_to='media/company_images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('name_uz', models.CharField(max_length=512, verbose_name='Name_uz')),
                ('name_eng', models.CharField(max_length=512, verbose_name='Name_eng')),
                ('name_ru', models.CharField(max_length=512, verbose_name='Name_ru')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('title_uz', models.CharField(max_length=512, verbose_name='title_uz')),
                ('title_eng', models.CharField(max_length=512, verbose_name='title_eng')),
                ('title_ru', models.CharField(max_length=512, verbose_name='title_ru')),
                ('poster', models.ImageField(upload_to='media/post_images')),
                ('short_description_uz', models.TextField(verbose_name='short_description_uz')),
                ('short_description_eng', models.TextField(verbose_name='short_description_eng')),
                ('short_description_ru', models.TextField(verbose_name='short_description_ru')),
                ('text_uz', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text_uz')),
                ('text_eng', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text_eng')),
                ('text_ru', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='text_ru')),
                ('slug', models.SlugField(unique=True, verbose_name='slug')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('title_uz', models.CharField(max_length=512, verbose_name='Title_uz')),
                ('title_eng', models.CharField(max_length=512, verbose_name='Title_eng')),
                ('title_ru', models.CharField(max_length=512, verbose_name='Title_ru')),
                ('description_uz', models.TextField(blank=True, null=True, verbose_name='Description_uz')),
                ('description_eng', models.TextField(blank=True, null=True, verbose_name='Description_eng')),
                ('description_ru', models.TextField(blank=True, null=True, verbose_name='Description_ru')),
                ('min_salary', models.IntegerField(verbose_name='Min_salary')),
                ('max_salary', models.IntegerField(verbose_name='Max_salary')),
                ('job_schedule', models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('shift', 'Shift'), ('flexible', 'Flexible')], max_length=30, verbose_name='Job_schedule')),
                ('work_location', models.CharField(choices=[('office', 'Office'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], max_length=30, verbose_name='Job_location')),
                ('city_uz', models.CharField(max_length=256, verbose_name='City_uz')),
                ('city_eng', models.CharField(max_length=256, verbose_name='City_eng')),
                ('city_ru', models.CharField(max_length=256, verbose_name='City_ru')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='main.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='main.company')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies', to='main.country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('fullname', models.CharField(max_length=256, verbose_name='Fullname')),
                ('phone_number', models.CharField(max_length=512, verbose_name='Phone_number')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('extra_description', models.TextField(verbose_name='Extra_description')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='main.country')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='main.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
