# Generated by Django 5.1.5 on 2025-01-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('fullname', models.CharField(max_length=512, verbose_name='fullname')),
                ('phone_number', models.CharField(max_length=512, verbose_name='Phone_number')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='company',
            name='image',
            field=models.ImageField(upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ImageField(upload_to='post_images'),
        ),
    ]
