# Generated by Django 5.1.5 on 2025-01-26 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('settings', '0002_alter_categorylanguage_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_languages', to='settings.language'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts_languages', to='main.post'),
        ),
    ]
