# Generated by Django 5.1.5 on 2025-01-26 12:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_categorylanguage_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorylanguage',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories_languages', to='main.category'),
        ),
        migrations.AlterField(
            model_name='categorylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='categories_languages', to='main.language'),
        ),
        migrations.AlterField(
            model_name='companylanguage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies_languages', to='main.company'),
        ),
        migrations.AlterField(
            model_name='companylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies_languages', to='main.language'),
        ),
        migrations.AlterField(
            model_name='countrylanguage',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries_languages', to='main.country'),
        ),
        migrations.AlterField(
            model_name='countrylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='countries_languages', to='main.language'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_languages', to='main.language'),
        ),
        migrations.AlterField(
            model_name='postlanguage',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts_languages', to='main.post'),
        ),
        migrations.AlterField(
            model_name='vacancylanguage',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies_languages', to='main.language'),
        ),
        migrations.AlterField(
            model_name='vacancylanguage',
            name='vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vacancies_languages', to='main.vacancy'),
        ),
    ]
