# Generated by Django 5.1.5 on 2025-01-27 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_postlanguage_language_alter_postlanguage_post'),
        ('settings', '0002_alter_categorylanguage_category_and_more'),
        ('vacancy', '0002_delete_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlanguage',
            name='post',
        ),
        migrations.RemoveField(
            model_name='postlanguage',
            name='language',
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated_at')),
                ('fullname', models.CharField(max_length=256)),
                ('phone_number', models.CharField(max_length=512)),
                ('email', models.EmailField(max_length=254)),
                ('extra_description', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='settings.country')),
                ('vacancy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='vacancy.vacancy')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='PostLanguage',
        ),
    ]
