# Generated by Django 5.1.5 on 2025-01-26 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_categorylanguage_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlanguage',
            name='slug',
        ),
    ]
